# Generated by Django 2.2.3 on 2019-08-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('Account', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=20)),
                ('Name', models.CharField(blank=True, max_length=15)),
                ('Gender', models.BooleanField(default=True)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.CharField(blank=True, max_length=25)),
                ('CreTime', models.DateField(auto_now_add=True)),
                ('LastUseTime', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-CreTime'],
            },
        ),
    ]
